//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOPVData
    {
        public string BBL { get; set; }
        public string PrimaryZoning { get; set; }
        public Nullable<float> LotFrontage { get; set; }
        public Nullable<float> LotDepth { get; set; }
        public Nullable<int> LotSquareFootage { get; set; }
        public string LotType { get; set; }
        public string Proximity { get; set; }
        public Nullable<float> BuildingFrontage { get; set; }
        public Nullable<float> BuildingDepth { get; set; }
        public Nullable<int> NumberOfBuildings { get; set; }
        public string Style { get; set; }
        public Nullable<int> YearBuilt { get; set; }
        public string ExteriorCondition { get; set; }
        public Nullable<int> FinishedSquareFootage { get; set; }
        public Nullable<int> UnfinishedSquareFootage { get; set; }
        public Nullable<int> CommercialUnits { get; set; }
        public Nullable<int> CommercialSquareFootage { get; set; }
        public Nullable<int> ResidentialUnits { get; set; }
        public string GarageType { get; set; }
        public Nullable<int> GarageSquareFootage { get; set; }
        public string BasementGrade { get; set; }
        public string BasementSquareFootage { get; set; }
        public string BasementType { get; set; }
        public string ConstructionType { get; set; }
        public string ExteriorWall { get; set; }
        public Nullable<float> NumberOfStories { get; set; }
        public string LastUpdated { get; set; }
        public string LotShape { get; set; }
    }
}
